# Minimal config. version is the only required field.
version = 1

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot"]

[merge.message]
# use title of PR for merge commit.
title = "pull_request_title" # default: "github_default"
# use body of PR for merge commit.
body = "pull_request_body"
# Strip HTML comments (<!-- some HTML comment -->) from merge commit body.
strip_html_comments = true
